name: Kotlin Test
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup jdk Kotlin 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 2.1.10

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test